//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Details
    {
        public int Client_Id { get; set; }
        public string Desination_at_client { get; set; }
        public string Client_Name { get; set; }
        public Nullable<decimal> Billing { get; set; }
        public Nullable<System.DateTime> Po_start_Date { get; set; }
        public Nullable<System.DateTime> Po_end_date { get; set; }
        public Nullable<int> Emp_id_fk { get; set; }
    
        public virtual Employee_details Employee_details { get; set; }
    }
}
