//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_details()
        {
            this.Bills = new HashSet<Bill>();
            this.Client_Details = new HashSet<Client_Details>();
        }
    
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Practice { get; set; }
        public string Designation_Lancesoft { get; set; }
        public decimal PaidTillNow { set; get; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Details> Client_Details { get; set; }
    }
}
