//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Employee_ProfileEntities1 : DbContext
    {
        public Employee_ProfileEntities1()
            : base("name=Employee_ProfileEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Client_Details> Client_Details { get; set; }
        public virtual DbSet<Employee_details> Employee_details { get; set; }
        public virtual DbSet<Userlogin> Userlogins { get; set; }
    }
}
